apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: flm
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql/mysql-server:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-user
          volumeMounts:
            - name: db-init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-init-sql
          configMap:
            name: db-init-sql   # assumes you created a ConfigMap with database.sql
